baseURL = "https://amarakon.github.io/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Amarakon"
theme = "fuji-nord"

hasCJKLanguage = false
enableEmoji = false
enableRobotsTXT = false

summaryLength = 50
paginate = 20

[params]
math = false
subTitle = "My website with the programs I use, the projects I maintain, and articles about many topics"
defaultTheme = "auto"

sourceURL = "https://github.com/amarakon/amarakon.github.io"

showWordCounter = true
showReadTime = false

disableDarkImage = true

[permalinks]
post = "/:section/:filename/"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
style = "nord"
guessSyntax = false
[markup.tableOfContents]
startLevel = 1
endLevel = 3

[menu]
[[menu.nav]]
name = "About"
url = "/about/"
[[menu.nav]]
name = "Programs"
url = "/programs/"
[[menu.nav]]
name = "Projects"
url = "/projects/"
[[menu.nav]]
name = "Articles"
url = "/articles/"

[[menu.link]]
name = "GitHub"
url = "https://github.com/amarakon"
[[menu.link]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCbZc671K2NxNbr1Kfqz6Fmg"

[security]
enableInlineShortcodes = true
